import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme/theme";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import { Providers } from "@/store/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className} style={{ margin: 0 }}>
				<Providers>
					<AppRouterCacheProvider>
						<ThemeProvider theme={theme}>
							<Navbar />
							{children}
						</ThemeProvider>
					</AppRouterCacheProvider>
				</Providers>
			</body>
		</html>
	);
}
